### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by KyleJune** [udibo/mock#1]
So far I have spys and stubs. I currently plan on adding a way to fake time for Date, setTimeout/clearTimeout, and setInterval/clearInterval.

Does anyone have any ideas for things that should be added or changed before tagging v1.0.0?

**Comment by TrueWill** [comment]
I managed to test [my module](https://github.com/TrueWill/paleontologist) with what you have now, so I'd say you're good! Thank you! 😄

**Comment by flemux** [comment]
It would be nice to have just a mockFunction... something similar to jest.fn.

I.e. we could build an object which has a number of mockFunctions which is then passed as an argument.  I.e. I'm building an application with Oak, and I'd like to generate a mock Context object.  Rather than have a class and have to stub / spy  each part of the context object one by one.

Not sure that makes sense....  Please let me know if I'm unclear, I could provide a better example.

**Comment by KyleJune** [comment]
I'm not too familiar with Jest, could you provide an example? I could look into either extending spy for that use case or creating a new function for mocking objects in the way you described.

**Comment by cdoremus** [comment]
I think you need a way to replace external dependencies for a module under test, for instance a `replace` function like is done in `testdouble.js` `replaceEsm` here: https://github.com/testdouble/testdouble.js#api.

**Comment by KyleJune** [comment]
> I think you need a way to replace external dependencies for a module under test, for instance a `replace` function like is done in `testdouble.js` `replaceEsm` here: https://github.com/testdouble/testdouble.js#api.

I'm not familiar with whether or not Deno has a way to specify a loader that can hook into the ES module loading mechanism like Node can. That is how testdouble said they did it [here](https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md#how-module-replacement-works-for-es-modules-using-import).

One workaround you could use is creating and exporting an object that has the dependencies your module uses. Then in the file use that object to access them. To mock the external dependencies, you would mock them on that exported object.

In [time.ts](https://github.com/udibo/mock/blob/master/time.ts#L13), I needed a way to mock functions like `setTimeout` so that I can verify it calls them correctly when it is suppose to. To do that I exported an object called `NativeTime` that has all these functions. Then instead of using `setTimeout` directly in that file, I would use `NativeTime.setTimeout` instead. From my tests, I could now mock the real `setTimeout` by mocking `NativeTime.setTimeout`.

**Comment by paambaati** [comment]
The ability to mock/stub `fetch` would be super-useful!

**Comment by KyleJune** [comment]
> The ability to mock/stub `fetch` would be super-useful!

This is possible already with stub. Although I guess I could make some sort of helper to make it easier. I'll need to think about what that helper would look like.

Here is a simple example where I mock the fetch function. The first code sample is a simple function that uses fetch. The second is a test that mocks fetch using the stub function.

```ts
export interface User {
  username: string;
  email: string;
}

export async function getUser(username: string): Promise<User> {
  const res: Response = await fetch(`https://example.com/users/${username}`);
  return res.json();
}
```

fetch returns a promise that resolves to a [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response), so to mock that behavior, I have the stub function return a promise that resolves to a fake Response that I create. If you want the behavior of the function to vary depending on the url, you could add the url arg to the stub function so that you can use it. The Response constructor takes a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) as its first argument, so I create one from the JSON I want to be the body for the response.

For getUser, I verify that it will return the User for the fake response I have fetch resolve to. For fetch, I want to verify it gets passed the correct url, so I use assertSpyCall to check that the first call has the correct url as its first and only arg.

```ts
import { getUser, User } from "./a.ts";
import {
  assertEquals,
  assertSpyCall,
  Stub,
  stub,
} from "./test_deps.ts";

Deno.test("getUser fetches user", async () => {
  const fetch: Stub<typeof globalThis> = stub(
    globalThis,
    "fetch",
    () =>
      Promise.resolve(
        new Response(
          new Blob([
            JSON.stringify(
              { username: "kyle", email: "github@kylejune.com" },
              null,
              2,
            ),
          ], { type: "application/json" }),
        ),
      ),
  );
  try {
    const user: User = await getUser("kyle");
    assertEquals(user, { username: "kyle", email: "github@kylejune.com" });
    assertSpyCall(fetch, 0, {
      args: ["https://example.com/users/kyle"],
    });
  } finally {
    fetch.restore();
  }
});
```

I hope this example helps. If any one has ideas for simplifying mocking fetch or examples of other projects that mock fetch in node or deno, I can look into possibly adding a helper to this module.

**Comment by manzanit0** [comment]
Something that might be useful is a simple way to also stub failures? I'm not sure if it's currently possible, I gave it a few tries and wasn't too sure, but I'm thinking something a long the lines of:

```ts
  const myStub = stub(imp, "action", resolvesNext([Promise.reject("fake error"), Promise.resolve()]));
```

Not sure if that would be the best API for it? IMO it makes sense because it makes it simple.

**Comment by KyleJune** [comment]
> Something that might be useful is a simple way to also stub failures? I'm not sure if it's currently possible, I gave it a few tries and wasn't too sure, but I'm thinking something a long the lines of:
> 
> ```ts
>   const myStub = stub(imp, "action", resolvesNext([Promise.reject("fake error"), Promise.resolve()]));
> ```
> 
> Not sure if that would be the best API for it? IMO it makes sense because it makes it simple.

The resolvesNext function wraps all values in the array in a promise. I didn't know this before, but apparently if one of the values rejects, the generator stops running. Which is why the first call it rejects with "fake error" but then it returns undefined for all future calls. You could write your own stub function that would do what you desire. The following example would reject on the first call then resolve to undefined on all the following calls.

```ts
const count = 0;
const myStub = stub(imp, "action", () => {
  if (count === 0) {
    return Promise.reject("fake error");
  }
  count++;
  return Promise.resolve();
});
```

I'd support a change to the function so that when passing an array with rejections in it, it will continue to resolve values in the array after the rejections. I believe it's possible to change it to behave that way.

Edit: I added an issue for the requested feature.

**Comment by KyleJune** [comment]
There won't be a v1.0.0 anymore. This module has been added to https://deno.land/std/testing.
