### ISSUE TITLE
stub function instead of object

### ISSUE THREAD

**Issue by finalight** [udibo/mock#10]
possible to stub a function directly instead of passing in an instance of the function where it belongs to?

reason being is because i'm moving towards functional programming and would like to do away with classes for implementation

**Comment by KyleJune** [comment]
The way the stub function works is that it takes the instance and replaces the property with a spy on the function that was previously there on the instance. For regular functions, the only way to replace a function would be to assign a new variable in its place. You can already do that with the spy function. The README.md file has an example that can be found [here](https://github.com/udibo/mock/tree/v0.9.5#spy). In the second example, isEven is being spied on. If you wanted to fake isEven, you could call spy with the fake function you want to serve as the isEven function for the test.
