### ISSUE TITLE
Does not compile with Deno 1.6.0

### ISSUE THREAD

**Issue by rracariu** [udibo/mock#8]
Reporting here as the failing dependency causes this issue.

See https://github.com/udibo/collections/issues/7

**Comment by KyleJune** [comment]
I'll upgrade this and my other modules Friday Night or on Saturday. Thank you for letting me know about the issue with 1.6.0.

**Comment by KyleJune** [comment]
This issue has been resolved in https://deno.land/x/mock@v0.9.4
